services:
  api:
    build:
      context: .
      target: production
    ports:
      - 4000:4000
    env_file: ./config/.env.production
  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
volumes:
  dbdata6:
